import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "./styles/Home.module.css";

export const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Chesslink App</title>
                <meta content="Generated by @rainbow-me/create-rainbowkit" name="description" />
                <link href="/favicon.ico" rel="icon" />
            </Head>

            <main className={styles.main}>
                <ConnectButton />

                <h1 className={styles.title}>Welcome to Chesslink</h1>

                <div className={styles.grid}>
                    <a className={styles.card} href="/player">
                        <h2>Deploy a Player &rarr;</h2>
                        <p>Holders can bet on your chess games.</p>
                    </a>

                    <a className={styles.card} href="https://wagmi.sh">
                        <h2>Bet on Games &rarr;</h2>
                        <p>Bet on other ongoing games to win.</p>
                    </a>
                </div>
            </main>
        </div>
    );
};
